### PR TITLE
testing CI

### PR DESCRIPTION
**Pull request by jpeeler**
Do not merge.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
We didn't register plugins to respond to the repo: https://github.com/openshift/release/commit/640a3125b1b00e33501daba0d983a3d3cd10641a

**Comment by jpeeler** [comment]
Test passed succesfully.

Note to self: if merge queue functionality desired add here: https://github.com/openshift/release/blob/ddc75efeb40cfcd28d7246d28466a8c2ef0338d0/cluster/ci/config/prow/config.yaml#L42

**Pull request closed without merging**
