### PR TITLE
Adding build support for archs other than amd64

### PR DESCRIPTION
**Pull request by Pensu**
This modifies the Dockerfile to add the build support for archs other than amd64.

### CODE REVIEW

**Comment by Pensu** [comment]
Hi @eriknelson @jpeeler, can you please review this?

**Comment by Pensu** [comment]
Hi @jmrodri, can we get this merged?

**Comment by jpeeler** [comment]
/approved
/lgtm

Despite many people being listed in the OWNERS file (myself included), I think the best person to ping for stuff like this is Shawn.

**Comment by mkumatag** [comment]
> /approved
> /lgtm
> 
> Despite many people being listed in the OWNERS file (myself included), I think the best person to ping for stuff like this is Shawn.

Thanks @jpeeler

**Pull request merged**
