### PR TITLE
Bump embedded tools

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
@jpeeler it looks like the Jenkins job is calling make build but expecting to get back content in _output/local/releases?  That would not work.

**Comment by jpeeler** [comment]
@smarterclayton I don't know why it expects content in .../releases, but it's just a warning and I've ignored it (do you know what I should do differently?) In this case, the unit test errors are the issue. And I have a feeling it's due to https://github.com/openshift/service-catalog/pull/9/files#diff-364c990d6b3397a631d8706b725c5046L15.

**Comment by smarterclayton** [comment]
Hrm.  Environment should never have been changed like that.  The build tools should correctly set up a go path inside of _output/local when they build - if they don't, it's either something wrong in constants.sh or an edge case that wasn't covered.

**Comment by smarterclayton** [comment]
Maybe a better question is, why are you calling the upstream test-unit segment?  Why aren't you using hack/test-go.sh?

**Comment by jpeeler** [comment]
I just didn't know any better. The unit tests can be adjusted to be executed like this:
OS_BUILD_ENV_PRESERVE="Makefile" hack/env make test-unit
But list_test_packages_under() needs to be adjusted to exclude tools/junitreport/* too. Is that acceptable/better?

Related to the above, I don't know of a better way to build catalog without rewriting all the import lines from kubernetes-incubator/ to openshift/ without changing the workingdir variable.

**Comment by smarterclayton** [comment]
The build-go scripts handle symlinking in the kube working dir under the root.  As we move to ci-operator we create the repo in the canonical location (which makes it easier), but build-go should do the right thing.

list_test_packages_under as provided by constants should be excluding tools, but it's easy enough to fix.  I'll look at the aos-cd-job on monday.

**Comment by smarterclayton** [comment]
Found the bug, the OS_BUILD_ENV_WORKINGDIR variable was missing `src`.

**Comment by smarterclayton** [comment]
No, all upstream projects (where the go code points to GitHub.com/kubernetes-*) need to be like this.

**Pull request merged**
