### PR TITLE
Enable passing a kubeconfig file to apiserver

### PR DESCRIPTION
**Pull request by kargakis**
Upstream cherry-pick of https://github.com/kubernetes-incubator/service-catalog/pull/2158

Also contains https://github.com/kubernetes-incubator/service-catalog/pull/2136 which we miss but on which 2158 is based on.

@jpeeler @jim-minter @pweil-

### CODE REVIEW

**Comment by jpeeler** [comment]
@kargakis generally we try to avoid carrying patches, but since 3.10 is frozen it would have to be done there. Do you need this for just 3.10 only? If so, I'll rebase this branch next release and apply the desired patches to the 3.10 branch (now).

**Comment by kargakis** [comment]
Yeah, ideally we want this in 3.10 even though we are most likely going to
GA in 3.11.

**Comment by jim-minter** [comment]
@jpeeler we need these patches to be able to deploy the service catalog as part of the "openshift on azure" project.  We need these changes to go into origin and enterprise 3.10 in the next release possible, as well as origin master as soon as possible.  Without them it won't deploy at all.

**Comment by jpeeler** [comment]
/lgtm
I was asking so that I see if I could rebase master with a new upstream release next week. But I'll go ahead and merge and sort the patch rebasing out later.

**Pull request merged**
